parameters: 
  signSteps: []
  
steps:
- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.7.0
  inputs:
    versionSpec: 4.7.0

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: scripts/setversion.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: .\crypto\src\crypto.csproj 
    arguments: -c $(BuildConfiguration) /p:PackageId="Portable.BouncyCastle" /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\Packages
  displayName: Build  
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\crypto\test\crypto.test.csproj
    arguments: -c $(BuildConfiguration)
  displayName: Run Tests
  
- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)
