configuration: Release
install:
  - cmd: choco install gitversion.portable -pre -y
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

assembly_info:
  patch: false
      
before_build:
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
  - cmd: nuget restore
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
build:
  verbosity: normal
  parallel: true
  project: BouncyCastle-PCL.sln
  
after_build:
  - cmd: '.\packages\gitlink\lib\net45\GitLink.exe . -f BouncyCastle-PCL.sln -u https://github.com/onovotny/BouncyCastle-PCL -s %APPVEYOR_REPO_COMMIT% -errorsaswarnings'  
  - cmd: nuget pack Portable.BouncyCastle.nuspec -version "%GitVersion_NuGetVersion%-build%GitVersion_BuildMetadataPadded%" -prop "target=%CONFIGURATION%"
  - ps: 'cmd /c "appveyor PushArtifact Portable.BouncyCastle.%GitVersion_NuGetVersion%-build%GitVersion_BuildMetadataPadded%.nupkg";if($lastexitcode -ne 0){$lastexitcode = 0}'