configuration: Release
image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

environment:
  SignClientSecret:
    secure: EvUuRb2cdsB5h7dJ49CkDDsZHHbwomGvMbcVcRsCSIp58IxVHFzAZrJSE+qpihtU
  SignClientUser:
    secure: 9nw9iBguE89m36udK51REeCIHSi5lAXmFIfS5LuAXio=

install:  
  - cmd: nuget install SignClient -Version 0.9.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

build_script:
  - cmd: msbuild /t:restore BouncyCastle.sln
  - cmd: msbuild /t:build BouncyCastle.sln 
  - cmd: msbuild /t:pack crypto\src\crypto.csproj /p:PackageId="Portable.BouncyCastle" /p:PackageOutputPath="%APPVEYOR_BUILD_FOLDER%"  
  
after_build:  
  - ps: '.\scripts\Sign-Package.ps1'  
  - cmd: dotnet test crypto\test\crypto.test.csproj --no-build

artifacts:
  - path: '*.nupkg'

test: off
