tag-prefix: 'pcl-[vV]'
legacy-semver-padding: 0
branches:
  pcl:
    mode: ContinuousDeployment    
    tag: beta
    increment: Inherit
    regex: pcl
  netstandard:
    mode: ContinuousDeployment    
    tag: beta
    increment: Inherit
    regex: netstandard